### ISSUE TITLE
cant send data back to sending socket

### ISSUE THREAD

**Issue by nayibor** [lpgauth/shackle#113]
hI,

hope u are good.
i needed some help with the shackle library.
i have been able to get it to work but am having some difficulties.
i have been trying to use shackle for a tcp client pool.
i am able to process the data received but cant seem to reply back to the sender of the data.
any idea why the recipient doesn't seem to receive the info sent back .
i wanted to know which part of the message also i received should identify the sender so i can send the info back to the sender.
thanks for the library also.

**Comment by ergl** [comment]
Hi! If I'm understanding you correctly, you don't know how to send the reply back to the original sender of the data inside the `handle_data/2`, right?

That function expects you reply with `{ok, [response()], State}`, where `response()` is `{external_request_id(), term()}`. This means that you have to return whatever request identifier you used to originally send your message to the server.

Check out an example with the [`arithmetic_tcp_client`](https://github.com/lpgauth/shackle/blob/f92c2e18e079f51dd28ce3f5210affe123538652/test/arithmetic_tcp_client.erl) module under the test folder:

https://github.com/lpgauth/shackle/blob/f92c2e18e079f51dd28ce3f5210affe123538652/test/arithmetic_tcp_client.erl#L103-L112

The client creates a new request id, and generates a new message with it:

https://github.com/lpgauth/shackle/blob/f92c2e18e079f51dd28ce3f5210affe123538652/test/arithmetic_protocol.erl#L34-L37

As you can see, the original request id is part of the binary we send to the server, which should reply back with the id so that the client can re-use it:

https://github.com/lpgauth/shackle/blob/f92c2e18e079f51dd28ce3f5210affe123538652/test/arithmetic_tcp_client.erl#L89-L98

Inside `parse_replies`, we extract the request identifier from the server message:

https://github.com/lpgauth/shackle/blob/f92c2e18e079f51dd28ce3f5210affe123538652/test/arithmetic_protocol.erl#L45-L48

As such, when `arithmetic_tcp_client:handle_data/2` returns, the pool is able to match the original request id to the original sender, and return it.

Hope this helps!

**Comment by nayibor** [comment]
hi.
thanks very much for the help and sorry for late reply.
thanks for the samples and its shed a lot of light on how the library works.
from our end whats happening is that the processes themselves are the direct connection between themselves and the tcp server.
there is no client sending a message with shackle acting as sort of a proxy.
i think thats the major difference.
so the thing is that when the shackle process gets the data,it just processes it and sends it  back if necessary.
so i was confused because there is no way to know how to send data directly to the requesting party.
thanks!!

**Comment by lpgauth** [comment]
You can still use shackle without a request_id() if your response are in order. All you have to do it keep a counter of requests out and requests in.

**Comment by nayibor** [comment]
please can u give me an example of that.
there is an example you cited above containing the counter  but that also contains the request id.

**Comment by lpgauth** [comment]
You need to keep two counters (one for requests out and one for requests in).

See https://github.com/lpgauth/buoy/blob/master/src/buoy_client.erl
